# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_kde_mix <- function(x, h, n, ord, betas) {
    .Call(`_fkde_f_kde_mix`, x, h, n, ord, betas)
}

f_kde_mix_grid <- function(x, h, n, ord, betas, ngrid, mn, MX) {
    .Call(`_fkde_f_kde_mix_grid`, x, h, n, ord, betas, ngrid, mn, MX)
}

f_kde_mix_binned <- function(x, h, n, ord, betas, nbin, min, max) {
    .Call(`_fkde_f_kde_mix_binned`, x, h, n, ord, betas, nbin, min, max)
}

df_kde <- function(x, h, n, ord) {
    .Call(`_fkde_df_kde`, x, h, n, ord)
}

